export const projects = [
  {
    id: 0,
    title: 'OneStream Live Studio',
    date: 'November 2021 - August 2024',
    description:
      'OneStream Studio is a cloud-based live streaming product that allows hosting events, recording videos, and live streaming while incorporating different media sources and innovative elements into your video streams. OneStream Studio has been designed for businesses, brands, gamers, and every individual content creator who hopes to take his live streaming game to the next level.',
    images: [
      '/assets/projects/osl/onboard.png',
      '/assets/projects/osl/studio.png',
      '/assets/projects/osl/prompter.png',
      '/assets/projects/osl/portrait.png',
    ],
    tags: [
      'React Js',
      'Redux',
      'Sagas',
      'GitLab',
      'Eslint',
      'Figma',
      'Centrifugo',
      'MaterialUI',
      'Ant Design',
      'Styled Components',
    ],
    category: 'web app',
    github: null,
    href: 'https://app.onestream.live/login',
  },
  {
    id: 1,
    title: 'OneStream Live - Webapp',
    date: 'January 2023 - July 2023',
    description:
      'OneStream Webapp is an innovative cloud-based live streaming platform that enables users to create professional-quality streams while broadcasting simultaneously to over 45 social media channels and websites. OneStream Live offers a user-centric experience with seamless integration between frontend design and backend functionality.',
    images: [
      '/assets/projects/osl/destinations.png',
      '/assets/projects/osl/osl/embed-settings.png',
      '/assets/projects/osl/login.png',
      '/assets/projects/osl/osl/pre-rec.png',
      '/assets/projects/osl/osl/theme-modes.png',
    ],
    tags: [
      'React Js',
      'Redux',
      'Sagas',
      'GitLab',
      'Prettier',
      'Eslint',
      'Figma',
      'Axios',
      'MaterialUI',
      'Styled Components',
    ],
    category: 'web app',
    github: null,
    href: 'https://app.onestream.live/login',
  },
  {
    id: 1,
    title: 'Ahit4Me',
    date: 'Feb 2021 - May 2021',
    description: `Ahit4Me stands for "Ability and Habit Improving Technology," a platform dedicated to enhancing personal growth. It combines technology with proven methods to help users develop skills and build lasting habits. Through personalized tools and actionable insights, Ahit4Me empowers individuals to achieve their full potential. It's your partner in creating a more productive and fulfilling life.`,
    images: [
      '/assets/projects/ahit4me/home.png',
      '/assets/projects/ahit4me/page3.png',
      '/assets/projects/ahit4me/page2.png',
      '/assets/projects/ahit4me/image.png',
      '/assets/projects/ahit4me/practice.png',
      '/assets/projects/ahit4me/sessions.png',
      '/assets/projects/ahit4me/web.png',
      '/assets/projects/ahit4me/page1.png',
    ],
    tags: ['Gatsby', 'CSS3', 'Material UI', 'Prettier'],
    category: 'web app',
    github: null,
    href: null,
  },
  {
    id: 2,
    title: 'InvoicesLab',
    date: 'May 2021 - November 2021',
    description:
      'The universal optimizer for high-tech manufacturing—automating, streamlining, and enhancing data entry, collaboration, and insights with AI.  An intelligent, data-informed platform to help you capture, engage, and interact with more customers in less time',
    images: [
      '/assets/projects/Invoiceslab/home.png',
      '/assets/projects/Invoiceslab/app.png',
      '/assets/projects/Invoiceslab/about.png',
      '/assets/projects/Invoiceslab/contact.png',
    ],
    tags: ['Gatsby', 'CSS3', 'Material UI', 'Prettier'],
    category: 'web app',
    github: null,
    href: null,
  },
  // {
  //   id: 3,
  //   title: 'Get An Intervention',
  //   date: 'Freelance project',
  //   description:
  //     'Get An Intervention is your go-to platform for finding trusted and effective addiction intervention services. Whether you’re seeking help for yourself or a loved one, our platform connects you with professional interventionists who can guide you on the path to recovery. We provide a streamlined process to help you access the support you need, when you need it most. Start your journey to healing today with Get An Intervention.',
  //   images: ['/assets/projects/get-an-intervention/hero.png'],
  //   tags: ['HTML 5', 'CSS 3', 'GitHub', 'Prettier', 'Perfect Pixel Extension'],
  //   category: 'web app',
  //   github: null,
  //   href: 'https://get-an-intervention-dev.vercel.app/',
  // },

  {
    id: 4,
    title: 'Regent Branding',
    date: 'Freelance project',
    description:
      'The Regent Branding highlights their expertise in digital marketing, branding, and web design, combining modern aesthetics with user-focused functionality to showcase their services and success stories',
    images: [
      '/assets/projects/regent/home.png',
      '/assets/projects/regent/blog.png',
      '/assets/projects/regent/contact.png',
      '/assets/projects/regent/about.png',
      '/assets/projects/regent/portfolio.png',
      '/assets/projects/regent/services.png',
    ],
    tags: ['Gatsby', 'CSS3', 'Material UI', 'Prettier'],
    category: 'web app',
    github: null,
    href: 'https://www.regentbranding.co.uk/regent-3-0/',
  },

  {
    id: 5,
    title: 'Cercling',
    date: 'Freelance project',
    description:
      'The universal optimizer for high-tech manufacturing—automating, streamlining, and enhancing data entry, collaboration, and insights with AI.  An intelligent, data-informed platform to help you capture, engage, and interact with more customers in less time',
    images: [
      '/assets/projects/cercling/home.png',
      '/assets/projects/cercling/contact.png',
      '/assets/projects/cercling/about.png',
    ],
    tags: ['NextJs', 'CSS3', 'Material UI'],
    category: 'web app',
    github: null,
    href: 'https://cercling.com/',
  },
];
